on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deployment
        env: 
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"

